//
//  SpringModels.swift
//  SpringApp
//
//  Created by Alexey Efimov on 16.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

typealias SpringRequest = Spring.Animation.Request
typealias SpringResponse = Spring.Animation.Request
typealias SpringViewModel = Spring.Animation.ViewModel

enum Spring {
 
    // MARK: Use cases
    enum Animation {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
