//
//  SpringAnimationPresenter.swift
//  SpringApp
//
//  Created by Alexey Efimov on 16.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SpringAnimationPresentationLogic {
    func presentSomething(response: SpringAnimation.Something.Response)
}

class SpringAnimationPresenter: SpringAnimationPresentationLogic {
    
    weak var viewController: SpringAnimationDisplayLogic?
    
    func presentSomething(response: SpringAnimation.Something.Response) {
        let viewModel = SpringAnimation.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
