//
//  SpringAnimationInteractor.swift
//  SpringApp
//
//  Created by Alexey Efimov on 16.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SpringAnimationBusinessLogic {
    func doSomething(request: SpringAnimation.Something.Request)
}

protocol SpringAnimationDataStore {
    
}

class SpringAnimationInteractor: SpringAnimationBusinessLogic, SpringAnimationDataStore {
    
    var presenter: SpringAnimationPresentationLogic?
    var worker: SpringAnimationWorker?
    
    func doSomething(request: SpringAnimation.Something.Request) {
        worker = SpringAnimationWorker()
        worker?.doSomeWork()
        
        let response = SpringAnimation.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
