//
//  SpringModels.swift
//  SpringApp
//
//  Created by Alexey Efimov on 16.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

typealias SpringRequest = Spring.Animate.Request
typealias SpringResponse = Spring.Animate.Response
typealias SpringViewModel = Spring.Animate.ViewModel

enum Spring {
 
    // MARK: Use cases
    enum Animate {
        struct Request {
            var rowIndex = 0
            var forceSliderValue: Float = 1
            var durationSliderValue: Float = 1
            var delaySliderValue: Float = 0
        }
        
        struct Response {
            let animation: Animation
        }
        
        struct ViewModel {
            let animation: String
            let curve: String
            let force: Double
            let duration: Double
            let delay: Double
            let damping: Double
            let velocity: Double
            let scale: Double
            let x: Double
            let y: Double
            let rotate: Double
            
            let forceText: String
            let durationText: String
            let delayText: String
        }
    }
}
