//
//  CodePresenter.swift
//  SpringApp
//
//  Created by Alexey Efimov on 18.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CodePresentationLogic {
    func presentSomething(response: Code.PresentCode.Response)
}

class CodePresenter: CodePresentationLogic {
    
    weak var viewController: CodeDisplayLogic?
    
    func presentSomething(response: Code.PresentCode.Response) {
        let viewModel = Code.PresentCode.ViewModel()
        viewController?.displayCode(viewModel: viewModel)
    }
}
